version: 'latest'
services:
  server:
    build: server/
    command: python3 ./server.py
    expose:
      - 1234
    ports:
      - "1234:1234"

  client:
    build: client/
    command: python3 ./client.py
    restart: "always"
    network_mode: host
    depends_on:
      - server